name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run SQL command to create table
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        sudo apt-get install postgresql-client
        psql $DATABASE_URL -f create_table.sql
